# Generated by Django 4.2.2 on 2023-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('linkResume', models.URLField()),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('OtherWebsite', models.CharField(blank=True, max_length=1000, null=True)),
                ('additionalComments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
